use std::{
    env,
    error::Error,
    fs,
    io::{self, Write},
    path::{Path, PathBuf},
};

fn main() {
    if let Err(error) = build_frontend() {
        panic!("failed to embed the Ignitify frontend: {error}");
    }
}

fn build_frontend() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let frontend_dir = manifest_dir.join("../..").join("frontend");
    let dist_dir = frontend_dir.join("dist");

    for path in [
        frontend_dir.join("index.html"),
        frontend_dir.join("package.json"),
        frontend_dir.join("pnpm-lock.yaml"),
        frontend_dir.join("vite.config.ts"),
        frontend_dir.join("src"),
    ] {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    use_prebuilt_frontend(&dist_dir)?;

    if !dist_dir.is_dir() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            "frontend build completed without producing frontend/dist",
        )
        .into());
    }

    let output_dir = PathBuf::from(env::var("OUT_DIR")?).join("frontend");
    if output_dir.exists() {
        fs::remove_dir_all(&output_dir)?;
    }
    fs::create_dir_all(&output_dir)?;

    let mut assets = Vec::new();
    collect_assets(&dist_dir, &dist_dir, &mut assets)?;
    assets.sort();

    for asset in &assets {
        let destination = output_dir.join(asset);
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::copy(dist_dir.join(asset), destination)?;
    }

    write_asset_module(
        &assets,
        &PathBuf::from(env::var("OUT_DIR")?).join("frontend_assets.rs"),
    )?;
    Ok(())
}

fn use_prebuilt_frontend(dist_dir: &Path) -> io::Result<()> {
    if dist_dir.is_dir() {
        println!("cargo:warning=embedding the existing frontend/dist bundle");
        Ok(())
    } else {
        Err(io::Error::new(
            io::ErrorKind::NotFound,
            "frontend bundle is missing; run `pnpm install --frozen-lockfile && pnpm run build` in frontend/ before running Cargo",
        ))
    }
}

fn collect_assets(root: &Path, directory: &Path, assets: &mut Vec<PathBuf>) -> io::Result<()> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_assets(root, &path, assets)?;
        } else if path.is_file() {
            let relative = path.strip_prefix(root).map_err(io::Error::other)?;
            assets.push(relative.to_path_buf());
        }
    }
    Ok(())
}

fn write_asset_module(assets: &[PathBuf], destination: &Path) -> io::Result<()> {
    let mut generated = fs::File::create(destination)?;
    writeln!(
        generated,
        "// Generated by crates/ignitify-api/build.rs. Do not edit."
    )?;
    writeln!(
        generated,
        "pub(crate) static EMBEDDED_FRONTEND: &[(&str, &[u8])] = &["
    )?;

    for asset in assets {
        let path = asset.to_string_lossy().replace('\\', "/");
        writeln!(
            generated,
            "    ({path:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/frontend/\", {path:?}))),"
        )?;
    }

    writeln!(generated, "];")?;
    Ok(())
}
