[package]
name = "ignitify-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
futures-util.workspace = true
hmac.workspace = true
ignitify-auth = { path = "../ignitify-auth" }
ignitify-control-plane = { path = "../ignitify-control-plane" }
ignitify-db = { path = "../ignitify-db" }
ignitify-domain = { path = "../ignitify-domain" }
ignitify-runtime-docker = { path = "../ignitify-runtime-docker" }
ignitify-runtime-remote = { path = "../ignitify-runtime-remote" }
ignitify-runtime-compose = { path = "../ignitify-runtime-compose" }
ignitify-terminal = { path = "../ignitify-terminal" }
jsonwebtoken.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
url.workspace = true
zeroize.workspace = true

[dev-dependencies]
age.workspace = true
argon2.workspace = true
http-body-util = "0.1"
tokio.workspace = true
tower = "0.5"
