[package]
name = "ignitify-runtime-compose"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ignitify-control-plane = { path = "../ignitify-control-plane" }
ignitify-domain = { path = "../ignitify-domain" }
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
yaml-rust2.workspace = true

[dev-dependencies]
tempfile = "3"
