[package]
name = "ignitify-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
age.workspace = true
axum.workspace = true
chrono.workspace = true
dotenvy.workspace = true
ignitify-api = { path = "../ignitify-api" }
ignitify-auth = { path = "../ignitify-auth" }
ignitify-backup-s3 = { path = "../ignitify-backup-s3" }
ignitify-control-plane = { path = "../ignitify-control-plane" }
ignitify-ingress-traefik = { path = "../ignitify-ingress-traefik" }
ignitify-monitoring = { path = "../ignitify-monitoring" }
ignitify-db = { path = "../ignitify-db" }
ignitify-dns = { path = "../ignitify-dns" }
ignitify-runtime-docker = { path = "../ignitify-runtime-docker" }
ignitify-runtime-remote = { path = "../ignitify-runtime-remote" }
ignitify-source-git = { path = "../ignitify-source-git" }
ignitify-terminal = { path = "../ignitify-terminal" }
ignitify-runtime-compose = { path = "../ignitify-runtime-compose" }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
uuid.workspace = true
