[package]
name = "ignitify-runtime-docker"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bollard.workspace = true
futures-util.workspace = true
ignitify-control-plane = { path = "../ignitify-control-plane" }
ignitify-domain = { path = "../ignitify-domain" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio.workspace = true
uuid.workspace = true
