[package]
name = "ignitify-dns"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hickory-resolver.workspace = true
ignitify-control-plane = { path = "../ignitify-control-plane" }
ignitify-db = { path = "../ignitify-db" }
ignitify-domain = { path = "../ignitify-domain" }
reqwest.workspace = true
serde.workspace = true
