[package]
name = "ignitify-monitoring"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
ignitify-db = { path = "../ignitify-db" }
reqwest.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
